version: "3.9"
services:
  registry:
    image: registry:2.8
    hostname: registry
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    volumes:
      - ${REGDIR:-/var/lib/registry}:/var/lib/registry
      - ${PWD}/certs:/certs
    environment:
      REGISTRY_HTTP_ADDR: '0.0.0.0:5000'
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.cert
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    ports:
      - 5000:5000
