apiVersion: v1
kind: Service
metadata: 
  name: database
  labels:
    svc: database
  namespace: database
spec:
  selector: 
    app.kubernetes.io/name: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
