services:
  mongo:
    image: mongo:jammy
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      - "./config:/config"
      - "./certs:/usr/share/ca-certificates/local"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret123
    # command: --config /config/mongod.conf
    ports:
      - 27017:27017
  
  express:
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret123
      ME_CONFIG_MONGODB_URL: mongodb://root:secret123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_SITE_SSL_ENABLED: true
      ME_CONFIG_SITE_SSL_CRT_PATH: /certs/localhost.cert
      ME_CONFIG_SITE_SSL_KEY_PATH: /certs/localhost.key
    volumes:
      - "./certs:/certs"
      - "./certs:/usr/share/ca-certificates/local"
    ports:
      - 8081:8081

  app:
    depends_on:
      - mongo
    image: node:22-alpine3.20
    working_dir: /app/nodejs
    command: "node main.js"
    volumes:
      - ".:/app"