apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    app: database
  namespace: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        app.kubernetes.io/name: database
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 120
          periodSeconds: 30
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret123