apiVersion: v1
kind: Service
metadata: 
  name: db-service
  labels:
    svc: database
  namespace: test1
spec:
  selector: 
    app.kubernetes.io/name: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 3306
  type: NodePort