services:
  database:
    image: mariadb:10.9-jammy
    volumes:
      - "../database:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_ROOT_PASSWORD: secret123
    ports:
      - 1306:3306
  webapp:
    depends_on:
      - database
    image: node:22-alpine3.20
    working_dir: /app/api
    command: "node main.js"
    volumes:
      - ".:/app"
    ports:
      - 1080:80
      - 1443:443