version: "3.9"
services:
  database:
    image: mariadb:10.9-jammy
    volumes:
      - ${PWD}/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: secret123
  web:
    build:
      context: .
    image: myweb:1.0
    ports:
      - 1080:80
