apiVersion: v1
kind: Service
metadata: 
  name: database-service
  labels:
    svc: database
  namespace: test1
spec:
  selector: 
    app.kubernetes.io/name: database
  ports:
    - protocol: TCP
      port: 
      targetPort: 
  type: NodePort